### ISSUE TITLE
Issue using AAD in the "Databricks Deploy Notebooks" release

### ISSUE THREAD

**Issue by RudyEvers** [DataThirstLtd/azure.databricks.cicd.tools#103] opened 2020-01-24 12:01 UTC
Via the "Databricks Deploy Notebooks" task I want to deploy various notebooks to a workspace. I use the service principal authentication instead of bearer. However nothing is deployed using AAD, but using Bearer it is deployed. Did i miss a something?
--

2020-01-23T14:45:58.5076945Z ##[section]Starting: Deploy Databricks Notebooks
2020-01-23T14:45:58.5169933Z ==============================================================================
2020-01-23T14:45:58.5169981Z Task         : Databricks Deploy Notebooks
2020-01-23T14:45:58.5170009Z Description  : Deploys a folder of Notebooks to your Databricks workspace
2020-01-23T14:45:58.5170053Z Version      : 0.8.1305
2020-01-23T14:45:58.5170082Z Author       : Data Thirst Ltd
2020-01-23T14:45:58.5170108Z Help         : 
2020-01-23T14:45:58.5170135Z ==============================================================================
2020-01-23T14:45:59.9883482Z Connecting via AAD
2020-01-23T14:46:00.6614433Z Clean false
2020-01-23T14:46:00.6616324Z Running without clean
2020-01-23T14:46:07.7127556Z 
2020-01-23T14:46:09.2780923Z 
2020-01-23T14:46:09.3114822Z ##[section]Finishing: Deploy Databricks Notebooks

**Comment by simondmorias** [comment] 2020-04-08 14:15
Closing as unable to reproduce

**Closed by simondmorias** 2020-04-08 14:15 UTC
